// Decodes a receiver capture file into one CSV per testpub message type.
//
// Payloads generated by ipc-relay-testpub (tools/testpub/telemetry.hpp) are
// decoded field by field and written to <out_dir>/<type>.csv:
//
//   board_health.csv   rail voltages/currents, temperatures, alarms
//   mode_status.csv    system mode and status flags
//   ptp_stats.csv      PTP (IEEE 1588) servo statistics
//   unknown.csv        any other payload, as hex
//
// A file is only created when the capture contains that message type. Every
// row starts with the capture record header (source_id, sequence,
// timestamp_ns, flags) and the testpub header (publisher_index,
// message_index). Rows are in capture order.
#pragma once

#include <cstdint>
#include <filesystem>
#include <map>
#include <string>

namespace ipcrelay::csvexport {

struct ExportResult {
    std::map<std::string, uint64_t> rows;  // file stem -> rows written
    std::string error;                     // empty on success
};

// Converts capture_path. On a malformed or truncated capture the CSVs hold
// every record before the error and error is set.
ExportResult export_capture(const std::string& capture_path, const std::filesystem::path& out_dir);

}  // namespace ipcrelay::csvexport
