// Frontend files compiled into ipc-relay-ctl (generated by embed_assets.cmake
// from tools/ctl/frontend/), so the control tool is a single binary.
#pragma once

#include <cstddef>

namespace ipcrelay::ctl {

struct WebAsset {
    const char* path;          // URL path, e.g. "/index.html"
    const char* content_type;
    const unsigned char* data;
    std::size_t size;
};

extern const WebAsset kWebAssets[];
extern const std::size_t kWebAssetCount;

}  // namespace ipcrelay::ctl
