# Generates a C++ source that embeds the ipc-relay-ctl frontend files
# (see backend/web_assets.hpp). Run with cmake -P:
#   -DBASE_DIR=<frontend dir> -DFILES=index.html,app.js,style.css -DOUTPUT=<file.cpp>
string(REPLACE "," ";" FILES "${FILES}")

set(arrays "")
set(table "")
set(index 0)
foreach(name IN LISTS FILES)
  file(READ "${BASE_DIR}/${name}" hex HEX)
  string(LENGTH "${hex}" hex_length)
  math(EXPR size "${hex_length} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
  string(REGEX REPLACE "((0x..,){16})" "\\1\n    " bytes "${bytes}")

  if(name MATCHES "\\.html$")
    set(type "text/html; charset=utf-8")
  elseif(name MATCHES "\\.js$")
    set(type "text/javascript; charset=utf-8")
  elseif(name MATCHES "\\.css$")
    set(type "text/css; charset=utf-8")
  elseif(name MATCHES "\\.svg$")
    set(type "image/svg+xml")
  else()
    set(type "application/octet-stream")
  endif()

  # Trailing 0 keeps the array non-empty for empty files; size excludes it.
  string(APPEND arrays "const unsigned char asset_${index}[] = {\n    ${bytes}0};\n\n")
  string(APPEND table "    {\"/${name}\", \"${type}\", asset_${index}, ${size}},\n")
  math(EXPR index "${index} + 1")
endforeach()

file(WRITE "${OUTPUT}" "// Generated by tools/ctl/embed_assets.cmake from tools/ctl/frontend/. Do not edit.
#include \"web_assets.hpp\"

namespace ipcrelay::ctl {

namespace {

${arrays}}  // namespace

const WebAsset kWebAssets[] = {
${table}};
const std::size_t kWebAssetCount = ${index};

}  // namespace ipcrelay::ctl
")
